openapi: 3.2.0
info:
  title: Fast Company By Url API
  version: 0.1.0
tags:
- name: Company By Url
paths:
  /api/company-by-url:
    post:
      summary: Api Company By Url
      operationId: api_company_by_url_api_company_by_url_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyByUrlRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Company By Url
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    CompanyByUrlRequest:
      properties:
        url:
          type: string
          title: Url
        api_key:
          type: string
          title: Api Key
      type: object
      required:
      - url
      - api_key
      title: CompanyByUrlRequest
