openapi: 3.2.0
info:
  title: Fast Prospecting API
  version: 0.1.0
tags:
- name: Prospecting
paths:
  /api/prospecting:
    post:
      summary: Api Prospecting
      operationId: api_prospecting_api_prospecting_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProspectingRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Prospecting
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ProspectingRequest:
      properties:
        api_key:
          type: string
          title: Api Key
        page:
          type: integer
          title: Page
          default: 1
        per_page:
          type: integer
          title: Per Page
          default: 10
        filters:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Filters
        sorting:
          anyOf:
          - items:
              additionalProperties: true
              type: object
            type: array
          - type: 'null'
          title: Sorting
      type: object
      required:
      - api_key
      title: ProspectingRequest
