openapi: 3.2.0
info:
  title: Fast Nomenclature API
  version: 0.1.0
tags:
- name: Nomenclature
paths:
  /api/nomenclature:
    post:
      summary: Api Nomenclature
      operationId: api_nomenclature_api_nomenclature_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NomenclatureRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Nomenclature
components:
  schemas:
    NomenclatureRequest:
      properties:
        api_key:
          type: string
          title: Api Key
        nomenclature_type:
          type: string
          title: Nomenclature Type
        parent:
          anyOf:
          - type: string
          - type: 'null'
          title: Parent
      type: object
      required:
      - api_key
      - nomenclature_type
      title: NomenclatureRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
