openapi: 3.2.0
info:
  title: Fast Company By Linkedin API
  version: 0.1.0
tags:
- name: Company By Linkedin
paths:
  /api/company-by-linkedin:
    post:
      summary: Api Company By Linkedin
      operationId: api_company_by_linkedin_api_company_by_linkedin_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyByLinkedinRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Company By Linkedin
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    CompanyByLinkedinRequest:
      properties:
        linkedin_url:
          type: string
          title: Linkedin Url
        api_key:
          type: string
          title: Api Key
      type: object
      required:
      - linkedin_url
      - api_key
      title: CompanyByLinkedinRequest
