openapi: 3.2.0
info:
  title: Fast Playground API
  version: 0.1.0
tags:
- name: Playground
paths:
  /playground:
    get:
      summary: Playground
      operationId: playground_playground_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Playground
